# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 10:16
from __future__ import unicode_literals

import comic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=comic.models.file_upload_to)),
                ('cover', models.ImageField(null=True, upload_to=comic.models.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ComicsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('comics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comics')),
            ],
        ),
    ]
