# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=100)),
                ('y', models.DecimalField(decimal_places=2, max_digits=100)),
                ('h', models.DecimalField(decimal_places=2, max_digits=100)),
                ('w', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
