# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20160810_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, to='comic.ComicsImage'),
        ),
    ]
