# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20160810_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicsimage',
            name='coordinates',
            field=models.ManyToManyField(blank=True, null=True, to='comic.Coordinate'),
        ),
    ]
