# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 13:24
from __future__ import unicode_literals

import comic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_auto_20160810_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=comic.models.file_upload_to),
        ),
    ]
