# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 13:45
from __future__ import unicode_literals

import comic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_auto_20160810_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadComics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=comic.models.file_upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=comic.models.file_upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='comics',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='comics',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comics',
            name='pdf',
        ),
        migrations.AddField(
            model_name='comics',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.UploadComics'),
        ),
    ]
