# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_auto_20160810_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.UploadComics'),
        ),
    ]
